### ISSUE TITLE
Dockerhub

### ISSUE THREAD

**Issue by jonathas** [DaveAldon/Sonarqube-with-Docker-and-M1-Macs#1]
Hi @DaveAldon,
could you add this to [Docker hub](https://hub.docker.com/) so my team doesn't have to build the image? I'd do that, but since the code is yours I thought about asking here instead :)

Thanks

**Comment by DaveAldon** [comment]
Yes sir! Added the link to the readme.

https://hub.docker.com/r/davealdon/sonarqube-with-docker-and-m1-macs

**Comment by jonathas** [comment]
thank you very much!
