### ISSUE TITLE
Update to SonarQube 9.3

### ISSUE THREAD

**Issue by patpatpat123** [DaveAldon/Sonarqube-with-Docker-and-M1-Macs#2]
Hello @DaveAldon,

First of all, I wanted to say thank you for this project, alongside the very well made tutorial websites.

Couple of days ago, SonarQube released version 9.3 officially.

May I ask if it is possible for this project to bump SonarQube to version 9.3 please?

I think this will help many M1 users who are using SonarQube.

Thanks a lot and good day!

**Comment by DaveAldon** [comment]
Thanks for your kind words! Absolutely, I updated the build to support the new version.

https://hub.docker.com/r/davealdon/sonarqube-with-docker-and-m1-macs

**Comment by patpatpat123** [comment]
Thanks a lot!
