### ISSUE TITLE
SonarQube release of version 9.4 officially out

### ISSUE THREAD

**Issue by patpatpat123** [DaveAldon/Sonarqube-with-Docker-and-M1-Macs#4]
Hello @DaveAldon,

Wanted to say thanks again for your help supporting version 9.3.

Couple of days ago, SonarQube released **version 9.4** officially.

May I ask if it is possible for this project to bump SonarQube to version 9.4 please?

Also, cold you please teach me "what did you do last time" for the bump to version 9.3?
Basically, if there are steps explaining how to bump versions, I would like to give it a go for version 9.4, 9.5, etc..

Thank you!

**Comment by DaveAldon** [comment]
Hi @patpatpat123, that's a great question. It's actually pretty easy to do once you know where to look.

Sonarqube updates a lot, and has a lot of builds underneath a major version. The `arm64.Dockerfile` needs the full build number to pull the image. So on line 89 of the `arm64.Dockerfile` I have a variable to hold the version. All I do is find that number and toss it in here:

```
ARG SONARQUBE_VERSION=9.4.0.54424
```

And to fully answer your question, how can you do this yourself, go to this sonarsource website that has the links to all possible binaries, and find the latest and plug that version into the above arg:

https://binaries.sonarsource.com/?prefix=Distribution/sonarqube/
![Screen Shot 2022-04-12 at 2 48 42 PM](https://user-images.githubusercontent.com/12663271/163034531-d1208d03-efc1-46fc-bfe4-62dc5e25e594.png)

I'll add this explanation to the readme as well.

**Comment by patpatpat123** [comment]
Understood, thank you!
