### ISSUE TITLE
Access denied 

### ISSUE THREAD

**Issue by mrparkersson** [DaveAldon/Sonarqube-with-Docker-and-M1-Macs#5]
I get this error after trying to start docker with this command `docker run -p9000:9000 sonarqubem1`

`docker: Error response from daemon: pull access denied for 9000, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.`

**Comment by DaveAldon** [comment]
Are you trying to build from the source repo, or from the docker hosted build?
